name: truck_eng_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.0.7
  audioplayers: ^6.0.0
  url_launcher: ^6.2.4
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
